export const metadata = {
	title: "Tennessee",
	description: "Generated by create next app",
};

export default function ChildLayout({ children }: { children: React.ReactNode }) {
	return (
		<div>
			Hello from Layout
			{children}
		</div>
	);
}
